### ISSUE TITLE
Разрешение экрана после перезагрузки 

### ISSUE THREAD

**Issue by ghost** [redrootmin/bzu-gmb#11]
Добрый вечер у меня такая  проблема после установки xanmod-cacule  и  после перезагрузки разрешение ставила на 4:3 680:450 и невозможно поменять лишь это разрешение стоит а видео карта 980 ti как можно решить эту проблему ubuntu system

**Comment by redrootmin** [comment]
xanmod-cacule  - не подходит для Nvidia, только классический xanmod
