### ISSUE TITLE
Zenity not found

### ISSUE THREAD

**Issue by Terromur** [redrootmin/bzu-gmb#7]
Заметил проблему насчёт Zenity в Kubuntu. Заодно решение проблемы нашёл, просто банального отсутствия у дистрибутива Zenity. Устанавливал под чистый Kubuntu установив все обновления. Вот решение проблемы https://command-not-found.com/zenity Добавьте в скрипт команду для людей, которые заметят вашу проблему и не поймут как её решить. А то лично я сначала подумал, что мой дистрибутив просто несовместим с вашей программой, в итоге решается довольно просто. 

Забыл упомянуть, что проблема начинается при запуске скрипта установки. Проблема выглядит так
bzu-gmb-beta4-installer.sh: 6: [: Illegal number: 
все хорошо этот скрипт не запущен из под root!
bzu-gmb-beta4-installer.sh: 13: zenity: not found

**Comment by xtrahigh** [comment]
To solve the problem, we should add a zenity installation check to each startup script:
`if !(dpkg -s zenity | grep -q installed); then sudo -S apt install -f -y zenity; echo 'zenity installed'; fi`

**Comment by barswert** [comment]
zenity установлен но при установке выдаёт:

bzu-gmb-beta4-installer.sh: 6: [: Illegal number: 
все хорошо этот скрипт не запущен из под root!
This option is not available. Please see --help for all possible usages
